export enum Configuration {
    PORT = 'PORT',
    JWT_SECRET = 'JWT_SECRET',
    DB_USER = 'DB_USER',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_HOST = 'DB_HOST',
    DB_PORT = 'DB_PORT',
    DB_SERVICE_NAME = 'DB_SERVICE_NAME',
    DB_DATABSE = "DB_DATABSE",
    API_KEY_MS = 'API_KEY',
    URL_MICROSERVICE_ORGANIC_STRUCTURE = 'URL_MICROSERVICE_ORGANIC_STRUCTURE',
    URL_MICROSERVICE_MINUTA = 'URL_MICROSERVICE_MINUTA',
  }