export enum Configuration {
  MONGOPORT = "MONGOPORT",
  MONGOHOST = "MONGOHOST",
  MONGOUSERNAME = "MONGOUSERNAME",
  MONGOPASSWORD = "MONGOPASSWORD",
  MONGODATABASE = "MONGODATABASE",
  MONGOURI = "MONGOURI",
}