export enum Configuration {
  MONGOPORT = "MONGOPORT",
  MONGOHOST = "MONGOHOST",
  MONGOUSERNAME = "MONGOUSERNAME",
  MONGOPASSWORD = "MONGOPASSWORD",
  MONGODATABASE = "MONGODATABASE",
  MONGOURI = "MONGOURI",
  GOOGLE_MAIL_HOST = "GOOGLE_MAIL_HOST",
  GOOGLE_MAIL_PORT = "GOOGLE_MAIL_PORT",
  GOOGLE_MAIL_USER = "GOOGLE_MAIL_USER",
  GOOGLE_MAIL_PASS = "GOOGLE_MAIL_PASS",
  GOOGLE_MAIL_SECURE = "GOOGLE_MAIL_SECURE"
}